# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI test only

on:
  push:
    branches: [ "feat/e2e-tests" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
    - run: npm run test:unit
    - run: npm run lint
    - name: Cypress run
      uses: cypress-io/github-action@v2
      with:
        start: 'npm run start:ci'
      env:
        CYPRESS_baseUrl: 'http://localhost:8080/'
